// <auto-generated />
using System;
using AttendanceTrackerInfrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceTrackerInfrastructure.Migrations
{
    [DbContext(typeof(AttendanceTrackerDbContext))]
    [Migration("20230912140243_Update_ForeignKey_In_WorkdayRecord_6")]
    partial class Update_ForeignKey_In_WorkdayRecord_6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendanceTrackerInfrastructure.Models.Admin", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("AttendanceTrackerInfrastructure.Models.Staff", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("AttendanceTrackerInfrastructure.Models.WorkdayRecord", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(1);

                    b.HasKey("Date");

                    b.HasIndex("StaffName");

                    b.ToTable("WorkdayRecords", (string)null);
                });

            modelBuilder.Entity("AttendanceTrackerInfrastructure.Models.WorkdayRecord", b =>
                {
                    b.HasOne("AttendanceTrackerInfrastructure.Models.Staff", "Staff")
                        .WithMany("Workdays")
                        .HasForeignKey("StaffName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("AttendanceTrackerInfrastructure.Models.Staff", b =>
                {
                    b.Navigation("Workdays");
                });
#pragma warning restore 612, 618
        }
    }
}
